/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublic_probeRouteImport } from './routes/api/public/__probe'
import { Route as ApiPublicWebhooksMonimeRouteImport } from './routes/api/public/webhooks/monime'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublic_probeRoute = ApiPublic_probeRouteImport.update({
  id: '/api/public/__probe',
  path: '/api/public',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMonimeRoute = ApiPublicWebhooksMonimeRouteImport.update({
  id: '/api/public/webhooks/monime',
  path: '/api/public/webhooks/monime',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public': typeof ApiPublic_probeRoute
  '/api/public/webhooks/monime': typeof ApiPublicWebhooksMonimeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public': typeof ApiPublic_probeRoute
  '/api/public/webhooks/monime': typeof ApiPublicWebhooksMonimeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/public/__probe': typeof ApiPublic_probeRoute
  '/api/public/webhooks/monime': typeof ApiPublicWebhooksMonimeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/api/public' | '/api/public/webhooks/monime'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/api/public' | '/api/public/webhooks/monime'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/public/__probe'
    | '/api/public/webhooks/monime'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiPublic_probeRoute: typeof ApiPublic_probeRoute
  ApiPublicWebhooksMonimeRoute: typeof ApiPublicWebhooksMonimeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/__probe': {
      id: '/api/public/__probe'
      path: '/api/public'
      fullPath: '/api/public'
      preLoaderRoute: typeof ApiPublic_probeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/monime': {
      id: '/api/public/webhooks/monime'
      path: '/api/public/webhooks/monime'
      fullPath: '/api/public/webhooks/monime'
      preLoaderRoute: typeof ApiPublicWebhooksMonimeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiPublic_probeRoute: ApiPublic_probeRoute,
  ApiPublicWebhooksMonimeRoute: ApiPublicWebhooksMonimeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
